kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fast2.ru-6
provisioner: cinder.csi.openstack.org
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: fast2.ru-6
  fsType: ext4
