kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fast2.ru-6a
provisioner: cinder.csi.openstack.org
parameters:
  type: fast2.ru-6a
  availability: ru-6a
  fsType: ext4
allowVolumeExpansion: true
