---
# universal.ru-9a.yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: universal.ru-9a
provisioner: cinder.csi.openstack.org
parameters:
  type: universal.ru-9a
  availability: ru-9a
  fsType: ext4
allowVolumeExpansion: true
