---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: universal.ru-9
provisioner: cinder.csi.openstack.org
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: universal.ru-9
  fsType: ext4
